### ISSUE TITLE
ICD 10 Cleaning Code Removing Valid Codes

### ISSUE THREAD

**Issue by jesse-sampson** [closedloop-ai/cv19index#17] opened 2020-04-02 20:18 UTC
Hey guys, I love this tool and am working with it right now, what a great contribution. 

One thing I noticed, the function to clean ICD 10 codes from the Tutorial seems to be only returning codes without dots and >3 characters. It was not 100% clear that if I supplied codes with dots that they would not make it through so I got stuck on that for a while. 

The bigger problem though is that there are valid ICD10 codes with only 3 characters, F99, R17, ... they appear in the CSSR docs but will never make it into a dataset from what I have tested. Thanks again just wanted to document these speed bumps.

I was able to resolve simply by adding another `return` after the `else:` since I did some cleaning on my ICD10s (too much :D) already. But I could see how for a more general case you'd want to add some other validation. 

`def cleanICD10Syntax(code):
    if len(code) > 3 and '.' not in code:
        return code[:3] + '.' + code[3:]
    else:
        code`

**Comment by DaveDeCaprio** [comment] 2020-04-03 00:21
Jesse, thanks for that.  We'll get that fixed in the checked in version.

**Comment by DaveDeCaprio** [comment] 2020-04-06 04:45
Thanks @jesse-sampson  - Also, I know you work with Medicaid populations, so you will want to switch to the new version of the model that will come with version 1.1.  That model is built with additional Medicaid data and will work better for non-Medicare populations.

**Closed as completed by DaveDeCaprio** 2020-04-06 04:45 UTC
Labels: help wanted

**Comment by jesse-sampson** [comment] 2020-04-08 03:40
That's awesome, thank you Dave!!

**Comment by outformatics** [comment] 2020-04-18 00:05
@DaveDeCaprio Thanks for your great work on cv19index!

About the old model (the one trained only on medicare data), are we saft to use the old model by feeding it the corrent features as intended, i.e., with 3 character ICD-10 codes mapping to CCSR?

How did the old model get trained? Did the training data map the 3 character ICD-10 codes to CCSR or not?

Thanks in advance!

**Comment by DaveDeCaprio** [comment] 2020-04-18 00:18
Glad it is working well for you.

 

Yes you are safe to use the old model with the current features, provided you are running that model on a Medicare population or a close proxy of it (generally 65 and older).  You should use the “xgboost_all_ages” model if you are running on healthy adults under 65.

 

Yes, the XGBoost model was trained including the 3 character ICD codes.  The error related to that was only in the code we had to run the model, not in the training process, which was done on the ClosedLoop platform and handles all of these transformations correctly.

 

Dave
